### PR TITLE
isort, black

### PR DESCRIPTION
**Pull request by nschloe**
The de-facto standard formatting for Python code is [black](https://github.com/psf/black). This PR applies [isort](https://github.com/PyCQA/isort) and black to one file, just to show what it'd look like.

### CODE REVIEW

**Comment by lukeolson** [comment]
eh... I have to say I'm not in favor of using black (at this point) -- I dislike some of the formatting choices.  I'd rather stick to the flake8/pylint/pydocstyle etc and cherry pick the things to set.  

`isort` is neat though -- hopefully we'd have to only apply this once (like your `pyupgrade` tip).

**Comment by nschloe** [comment]
> eh... I have to say I'm not in favor of using black (at this point) -- I dislike some of the formatting choices. I'd rather stick to the flake8/pylint/pydocstyle etc and cherry pick the things to set.

Sure thing. I remember feeling a little odd about black as well, but I got used to it. What I find neat about it is that you _cannot_ configure it. I could finally put the burden of deciding which indentation style to use on some authority's shoulders.

> isort is neat though -- hopefully we'd have to only apply this once (like your pyupgrade tip).

I'll open a separate PR for it.

**Comment by lukeolson** [comment]
> > eh... I have to say I'm not in favor of using black (at this point) -- I dislike some of the formatting choices. I'd rather stick to the flake8/pylint/pydocstyle etc and cherry pick the things to set.
> 
> Sure thing. I remember feeling a little odd about black as well, but I got used to it. What I find neat about it is that you _cannot_ configure it. I could finally put the burden of deciding which indentation style to use on some authority's shoulders. -- No more style configs.

Ok, I've added a note in #285 to add linting to the ci... I have a start on it.  Who knows, maybe we'll need to reopen this :)

> 
> > isort is neat though -- hopefully we'd have to only apply this once (like your pyupgrade tip).
> 
> I'll open a separate PR for it.

Thanks!

**Comment by nschloe** [comment]
> Ok, I've added a note in #285 to add linting to the ci... I have a start on it. Who knows, maybe we'll need to reopen this :)

#286

**Pull request closed without merging**
