### PR TITLE
Standard AMG interpolation, unknown approach for systems, coarse grid visualization

### PR DESCRIPTION
**Pull request by waynemitchell**
This adds standard Ruge-Stuben interpolation for classical AMG. 
Also, performed some surgery to ruge_stuben_solver() in order to enable the "unknown" approach for systems.
Lastly, functionality was added for visualizing coarse grids for classical AMG. If the user passes in a list of dof locations ('verts'), these locations will be transferred to all coarse grids so that visualizations of cf splittings on each level may be dumped to vtu files.

### CODE REVIEW

**Comment by jbschroder** [comment]
I think that this pull request might go better into the complexity branch, which is where Ben S. needs it.  I just moved the standard interpolation into the complexity branch, but this still leaves the unknown based approach and visualization functionalities.  My thoughts on those are

(1) We usually leave the visualization as a post-processing step, so we probably don't want to include visualization information in the hierarchy.  If you set the "keep=True" option, then the splitting and strength matrix are also stored at each level, allowing you to do visualizations as post-processing.

(2) I like the way that the unknown based approach is done, but the get block diagonals code looks like it is pretty slow for large matrices.  Any time you have to loop over all the degrees-of-freedom in Python, things aren't very fast.  Can we replace the loop by taking slices like
A1 = A[0:K,:][:,0:K] ?
This is probably much faster.

Last, I still got divide by zeros from standard interpolation for the 
  gallery.load_example['bar']
problem (linear elasticity in 2D).  I inserted a line to check for 0 denominators, but I don't know if this is correct.

So...maybe 2 good TODOs for this code is
(1) Figure out if standard interpolation is correct
(2) Update the unknown based approach for speed and integrate into the complexity branch (which will get pulled into master later)

**Comment by waynemitchell** [comment]
Jacob,
Sounds good to me. I've got my comprehensive exam coming up next week, so
I'm focused on that for the time being. I'll take a look at this and try to
get this stuff into Ben's branch next week.
Thanks,
Wayne

**Comment by ben-s-southworth** [comment]
Hey Wayne,
Any luck with the standard interpolation stuff?
-ben

**Comment by waynemitchell** [comment]
Jacob and Ben,
Ok, I've finally gotten around to looking at this again.
Using slices for the extract_diagonal_blocks() function was quite simple (I
think when I wrote this originally, I didn't realize you could just use the
same slicing syntax on the scipy sparse matrices).
As far as debugging standard interpolation, I see that for the 'bar'
example, we get zeros for the inner_denominator in ruge_stuben.h. This
means that when we sum over the connections between node k (a strongly
connected fine point) and the other strongly connected C points, we get
cancellation to zero.
This cannot happen if all off-diagonal elements are the same sign (as is
the case for M matrices). The 'bar' example matrix doesn't have this nice
property, however, so we can get cancellation.
I don't know whether there is a standard fix for this problem or not. I've
included John on this email to get his input here. As I understand it, the
idea is to account for the contribution from fine node k by spreading its
contribution to the other connected C points. The inner denominator sum
serves as part of a weighted averaging used when spreading node k's
contribution to the other C points. With this in mind, it sort of makes
sense to me that you could sum absolute values for the inner denominator
(thus avoiding cancellation). I'm not sure you'd end up with the
appropriate sign though, as I've not really thought much about the
interpolation weight formula in a non- M matrix context...
Thoughts from yall on this? Let me know if it's not clear what I'm talking
about. I'm sure John probably knows of some solution here.
Thanks,
Wayne

**Comment by waynemitchell** [comment]
Hi Wayne,


Suppose i is the point you want to interpolate to. This is from C-points j that i is strongly connected to.

(Call this S_i.) As you noted, in doing this secondary approximation for e_k for k in F or weak connections

in the neighborhood of i, you have to look at connections from k to points in S_i, and this sum over all these

connections can be zero. The easiest way to handle this is to take this secondary sum only over points also

in S_k (which are presumably all the same sign). By the usual choice of the coarse grid, this set should be

nonempty, so the sum should be nonzero. (You could also take this sum over just all "right-sign" connections,

again keeping the denominator nonzero.)


John


________________________________

**Comment by waynemitchell** [comment]
Ok, so I've tried out John's suggestions. If I take the sum only over
points in S_i intersect S_k, as John suggested, I still get some bad
behavior. Sometimes this set is empty (resulting in a zero denominator) and
sometimes I even still get cancellation to zero. I suppose this is due to
the coarsening and strength of connection strategies not giving us what we
expect for this particular problem.
So, using John's other suggestion, I tried just taking the sum over all
"right-sign" connections. That is, I only add a_kl to the denominator if it
is the same sign as a_kj. This fixes the zero denominator problem. I tested
this strategy on a Poisson problem (just to make sure I didn't goof up
something in the implementation) and got expected results. Applying this to
the 'bar' test problem yields a converging AMG iteration, but the
convergence seems quite slow. I'm not sure exactly what the 'bar' problem
is (Jacob said it was some kind of linear elasticity problem), so I don't
know if we expect good AMG convergence here. Also, if it is a system, I'd
need the block structure of the matrix to apply the unknown approach. As
is, I'm just naively forming an AMG hierarchy on the whole matrix to
achieve the slow convergence.
Anyway, if this all sounds kosher to Jacob and Ben at this point, we can go
ahead with putting this all into Ben's pyamg branch. Let me know if yall
are ready to proceed, and Ben and I will work on getting everything merged
in.
Thanks,
Wayne

**Comment by waynemitchell** [comment]
There are (obviously) a lot of options built into any AMG implementation. Going strictly

by the classical description, connections from j to points in S_j are only "right-sign", and, like I

said, the classical C-point choice is meant to ensure that S_i intersect S_j is nonempty. That said,

as you found, some options don't play well together. I'm not sure there's any universally

agreed upon way to handle things when they go wrong. (One thing I've done as a backup is

to say that, whenever this secondary denominator is zero, we just assume that e_j = e_i &

add a_ij to the diagonal a_ii. While this avoids division by zero, it can still produce bad results.

If the sum is just near zero, you may technically be able to interpolate constants (if the matrix

row for i is zero-row sum), but you can get large positive & negative interpolation weights, which

isn't especially ideal.)


For any symmetric problem, AMG should converge (or at least not diverge). If the beam

problem is what I think it is, I'd expect slow convergence using the unknown-based

approach. For a blind application of essentially scalar AMG, I'd expect worse, although it

might be hard to tell the difference (depending on beam length).


John

________________________________

**Comment by lukeolson** [comment]
closing.  Superseded by #244

**Pull request closed without merging**
