### PR TITLE
Better version check

### PR DESCRIPTION
**Pull request by nschloe**
I had a problem with numpy nightlies (`1.13.0dev5a62f4`). Fixed now.

@lukeolson

### CODE REVIEW

**Comment by nschloe** [comment]
Another option would probably be to use `distutils`' `LooseVersion`, cf. http://stackoverflow.com/a/6972866/353337.

**Comment by nschloe** [comment]
Bumped into this again with scipy master,
```
ValueError: invalid literal for int() with base 10: 'dev0+01950ad'
```

**Comment by lukeolson** [comment]
This looks good.  Thanks @nschloe .  I'll roll out a new minor release.

**Comment by nschloe** [comment]
Rolling out a minor release would indeed simplify my current testing workflow a lot.

**Pull request merged**
