### PR TITLE
MNT Removes usage of deprecated np.float, np.bool, np.int

### PR DESCRIPTION
**Pull request by thomasjpfan**
Uses `float` instead of `np.float` to keep the same behavior.

### CODE REVIEW

**Comment by lorentzenchr** [comment]
Closes #265.

**Review by lorentzenchr — APPROVED** [review]
LGTM
In pyamg/graph_ref.py, there is an instance of `np.int`, in pyamg/amg_core/tests/test_bind_examples.py `np.bool`.

**Comment by lukeolson** [comment]
I should have just grabbed this to start -- but ended up going with specifying the precisions in most if not all spots.  I believe it's consisent.
   https://github.com/pyamg/pyamg/commit/dec099b5548674880fa2d59c775bb0095fb476a0

Anyway thanks for this!

**Comment by thomasjpfan** [comment]
@lukeolson Thank you for fixing this and tagging a new release!

**Pull request closed without merging**
